version: "3"

services:
  flexi:
    container_name: flexi
    build: .
    volumes:
      - ./:/var/www/html:cached
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/apache2/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./xdebug:/tmp/xdebug
    ports:
      - "8080:80"
