name: Release Builder

on:
  create:
    tags:
      - 'v*'

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: get_changeLog
        id: changelog
        # Get the history of changes from the last tag to HEAD
        run: |
          last_tag=$(git describe --tags --abbrev=0)
          changelog=$(git log --oneline --pretty=format:"- %s" $last_tag..HEAD)
          echo "changelog=$changelog" >> $GITHUB_OUTPUT
          echo "tag=$last_tag" >> $GITHUB_OUTPUT 

      - name: Cache Composer
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Format Code
        run: composer run-script format

      - name: Test Code
        run: composer run-script test  # replace with check after fix psalm permissions

      - name: Clean Vendor Dev Dependencies
        run: |
          rm -rf ./vendor
          composer install --no-dev
          

      - name: Create Zip
        run: |
          mkdir .flexi
          cp -r * .flexi
          mv .flexi flexi
          zip -r flexi.zip flexi

      - name: Build Artifact
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: ./flexi.zip
          allowUpdates: true
          name: Release ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.changelog }}